name: build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:

      - name: checkout
        uses: actions/checkout@v6

      - name: build-image
        run: |
          podman build \
            --network host \
            --pull \
            --squash-all \
            --tag rust:alpine-mimalloc \
            .

      - name: test-image
        run: |
          podman run \
            --init \
            --network host \
            --rm \
            --tmpfs /tmp:exec \
            --volume $PWD:/workspace \
            --workdir /workspace \
            rust:alpine-mimalloc \
            /workspace/test.sh
          MIMALLOC_VERBOSE=1 ./bin/names
          file ./bin/names
